### ISSUE TITLE
Calculate total quantity ordered from list of deliveries

### ISSUE THREAD

**Issue by wjwillemse** [MikeBrink/python-picnic-api#2]
Great package Mike! I was wondering whether it would be possible to calculate the total quantity ordered during a certain period or from a list of deliveries, and also the average daily quantity consumed. Then we could predict when an item should be ordered.

**Comment by MikeBrink** [comment]
Hi,

Sorry for the late response, but glad to hear you are enjoying the repo!

You are already able to achieve this with the current version! I'll give an example below:

```python
from python_picnic_api import PicnicAPI

picnic = PicnicAPI(username='username', password='password')
picnic.get_deliveries()
```

This will return a list in which every element is a dict for every delivery.
