### ISSUE TITLE
api version 15 no longer working

### ISSUE THREAD

**Issue by rtoma** [MikeBrink/python-picnic-api#3]
login on 15 returns:
```
HTTP/2 403
server: awselb/2.0
date: Tue, 24 Nov 2020 21:44:29 GMT
content-type: text/html
content-length: 118
```

changing it to 16 returns:
```
HTTP/2 200
date: Tue, 24 Nov 2020 21:44:41 GMT
content-type: application/json
server: nginx/1.13.8
...
```

being curious I iterated api versions 1..50, all return 200 except for 15. weird.

**Comment by MikeBrink** [comment]
Thanks for raising the issue and doing some checking which versions do work and which do not. Version 15 was the highest number available when I developed this package last summer

I'll have a look into this tomorrow. I also want to add some proper error handling in the next version!

**Comment by MikeBrink** [comment]
Weird, it seems like Picnic restored the issue on their side. I am able to use api version 15 again, but it seems that their api versioning has changed a bit since I am also still able to use any number now.

**Comment by rtoma** [comment]
Indeed. It now accepts anything (eg numbers and strings), as long as it is non-empty. Thanks for looking into this issue. Feel free to close it.
